### ISSUE TITLE
No songs available to display.

### ISSUE THREAD

**Issue by Adrigamer2950** [lolollllo/discord-portable-player#102]
When I run my bot and play music for under 10 minutes, it just crashes with this feedback
![image](https://user-images.githubusercontent.com/58531641/182021002-8db123af-abe9-4e2d-b77d-774eb33d4017.png)

**Comment by lolollllo** [comment]
I haven't had this problem before, Though i'll look into it!

**Comment by lolollllo** [comment]
Could you please provide the stack trace?
And the version of Discord portable player your using? (npm ls discord-portable-player) and your node-version!

**Comment by Adrigamer2950** [comment]
node version: v16.16.0
discord-portable-player version: ^2.1.6

**Comment by lolollllo** [comment]
Could you leave a DM for me on Discord?
Tag: `Nex ♪#2221`

**Comment by lolollllo** [comment]
It's caused when `toString` is called when there's no songs available.
SRC: https://github.com/lolollllo/discord-portable-player/blob/a3b9defd6cd8ba75a314fae8b7fb3bdcd458304e/src/Structures/Queue.ts#L784

**Comment by lolollllo** [comment]
If you have less than 2 tracks, the error will be thrown as well!
