### ISSUE TITLE
using Queue#seek method emits trackStart event

### ISSUE THREAD

**Issue by Olebeh** [lolollllo/discord-portable-player#45]
ik there's a bunch of report in a short time, but want to report everything so the player will be completely bugless (maybe). So, the problem whenever i try to seek current track, it emits trackStart, i don't know if it's a feature, but if it is, i think this is really stupid idea

**Comment by lolollllo** [comment]
Well its kinda meant to happen, (not because we want it to), the seek method uses the play method so it emits the trackStart event.
