### ISSUE TITLE
Suggestion: if everyone in the current vc deafens, the playback will be paused

### ISSUE THREAD

**Issue by Olebeh** [lolollllo/discord-portable-player#60]
So, if everyone who's in the voice channel right now deafens, the bot should pause the music until someone undeafens. i think that's pretty cool feature

**Comment by lolollllo** [comment]
Util.isEveryoneDeafened() is a temporary placement for this!
Introduced in `1.6.1`!

**Comment by Olebeh** [comment]
thanks for this, but i looked to the code, and noticed that there's no filter for bots. So, if there's a bot in a vc, and he's not deafened, the function will always return false

**Comment by lolollllo** [comment]
> thanks for this, but i looked to the code, and noticed that there's no filter for bots. So, if there's a bot in a vc, and he's not deafened, the function will always return false

Fixed in `1.6.3`

**Comment by lolollllo** [comment]
Er, so found a bug where it always returns false since we don't filter out bots in the channel members. Will be publishing `1.6.4` tomorrow with a fix!

**Comment by lolollllo** [comment]
fixed
